#@package _global_

task_name: t6_textile
ssl_model_size: base
train_data_budget: 1.0
val_data_budget: 0.5
experiment_name: ${sensor}_${task_name}_${ssl_name}_vit${ssl_model_size}_${train_data_budget}
seed: 42

hydra:
  job:
    id: ${now:%Y.%m.%d}_${now:%H-%M}
  run:
    dir: ${paths.log_dir}/${hydra.job.id}_${experiment_name}

wandb:
  project: ${task_name}_${sensor}
  group: ~
  tags: ["${ssl_name}"]

trainer:
  max_epochs: 51
  validation_frequency: 5
  sanity_validate: true
  save_checkpoint_dir: ${paths.output_dir}/checkpoints
  checkpoint_interval_type: 'log'
  max_task_checkpoints: 10
  save_probe_weights_only: True

data:
  train_data_budget: ${train_data_budget}
  val_data_budget: ${val_data_budget}

test:
  data:
    dataset_name: [
      test/broadcloth,
      test/cotton,
      test/denim,
      test/fleece,
      test/hairy,
      test/leather,
      test/other,
      test/polyester,
      test/suit,
      test/wool,
      test/corduroy,
      test/crepe,
      test/flannel ,
      test/garbardine,
      test/knit,
      test/net,
      test/parka,
      test/satin,
      test/velvet,  
      test/woven,
    ]
    look_in_folder: true
    batch_size: 200
  tester:
    _partial_: True
    _target_: tactile_ssl.test.TestTextileSL
  path_outputs: ${paths.tacbench_dir}/${task_name}_${sensor}/

task:
  _target_: tactile_ssl.downstream_task.TextileSLModule
  checkpoint_task: ~

  model_encoder:
    _target_: tactile_ssl.model.vit_${ssl_model_size}
    img_size: ${data.dataset.config.transforms.resize}
    in_chans: 6
    pos_embed_fn: sinusoidal
    num_register_tokens: 1

  model_task:
    _target_: tactile_ssl.downstream_task.TextileLinearProbe
    embed_dim: ${ssl_model_size}
    num_heads: 12
    depth: 1
    num_classes: 20

  checkpoint_encoder: ${paths.encoder_checkpoint_root}/${ssl_name}_vit${ssl_model_size}.ckpt
  train_encoder: false
  encoder_type: ${ssl_name}

  weights_classes: ${data.dataset.config.weights_classes}
  class_labels: ${data.dataset.config.class_labels}

  optim_cfg:
    _partial_: True
    _target_: torch.optim.Adam
    lr: 0.0001

  scheduler_cfg: ~